#!/usr/bin/env bash

[ $# -ne 1 ] && \
    printf "RAT: Run a test\nUsage:\n    $0 <test-identifier>"&& \
    exit 1;


num=$(printf "%04d" $1)
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -Bbuild -H.
cmake --build build/ --target $num.t && ./build/"${num}".t
